# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c06a42c7db1fc2fb1211a8396faa5341c54dcaa72a7b535ec8b789ec9ada6a310b56b9314054d8f8fab3fe248cf959dda97bd606e77b67377f2fcddb1d8c2a3

test:
  secret_key_base: f428d8c195c6ab35e415f12d5a3b8dd688d70708d146901fa8b405d767ce6b522b28a1a5ecb38d7048281b14ffce41e167664e0377513826cabc1f736a9730af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
